Update patch set 4
Patch Set 4:

Formatter complains about:
jenkins_jobs.errors.JenkinsJobsException: print $1 parameter missing to format #!/bin/bash

Patch-set: 4
Label: Verified=0