Update patch set 3
Patch Set 3:

Flake8 Violations: 13
First 5 shown
---
 ./utils/test/testapi/opnfv_testapi/common/message.py:3:1: E731 do not assign a lambda expression, use a def
 ./utils/test/testapi/opnfv_testapi/resources/scenario_handlers.py:8:1: F401 'opnfv_testapi.common.message' imported but unused
 ./utils/test/testapi/opnfv_testapi/resources/scenario_handlers.py:86:13: F811 redefinition of unused 'message' from line 8
 ./utils/test/testapi/opnfv_testapi/resources/scenario_handlers.py:313:80: E501 line too long (82 > 79 characters)
 ./utils/test/testapi/opnfv_testapi/tests/unit/test_base.py:83:1: W293 blank line contains whitespace

Patch-set: 3