Update patch set 5
Patch Set 5: Code-Review-1

I couldn't test this on my computer. It complained about not having conf.py in correct place.

Error: Config directory doesn't contain a conf.py file.

This could either be due to me having wrong configuration for sphinx or docu-*.sh scripts should execute sphinx with parameter pointing to conf.py.

Ps. please disregard my -1 if this works for others and/or LF.

Patch-set: 5
Label: Code-Review=-1