Problem with rally_sanity results
after refactor, details in rally_sanity became 'unicode', which contains
built-in 'format' method, which is not processed correctly
error message:
File
"/usr/local/lib/python2.7/dist-packages/opnfv_testapi/resources/models.py",
	line 36, in _format
	for h in dicts[k]]
	KeyError: u"u'details'"

JIRA: FUNCTEST-723

Change-Id: Ieae5fdfd2a044909784cbb4766a5d25f4bbafcea
Signed-off-by: SerenaFeng <feng.xiaowei@zte.com.cn>