Update patch set 1
Patch Set 1: Code-Review-1

(2 comments)

Note, renaming of the file is needed

when manually renamed, I can access to the method
see http://213.77.62.197/dashboard?project=qtip&case=network_test_suite


but there is an error in http://213.77.62.197/dashboard?project=qtip&case=compute_test_suite => cast issue 'y1': data['details']['index'],
TypeError: string indices must be integers

Patch-set: 1
Label: Code-Review=-1