jjb: infra: bifrost-cleanup-job: Fix job triggers
Add new trigger when a patchset is abandoned and drop the one for
'recheck' and 'reverify' comments since the logs will be eventually
deleted when the patchset is merged or abandoned. Moreover, fix quoting
for the BIFROST_GS_URL variable which prevented logs from being deleted
properly. This fixes the following error:

CommandException: No URLs matched:
gs://artifacts.opnfv.org/cross-community-ci/openstack/bifrost/$GERRIT_NAME/$GERRIT_CHANGE_NUMBER/

Change-Id: I8f6ca7a9b2af4a7a4b204f15abf6a223144637a6